---
- hosts: vagrant
  vars_files:
    - vars.yml
  gather_facts: false
  sudo: true

  roles:
    - common
    - nginx
    - supervisor
    - redis
    - postgresql
    - project_data
    - django
    - gunicorn
    - celery