---
project_name: vault-backend
project_repo_url: git@github.com:ophio/vault-backend.git
project_repo_remote: origin
project_path: /home/{{user}}/vault-backend
domain_name: vault.ophio.co.in
celery_app: config
